### ISSUE TITLE
mc_rtc fails to pass test-mc_rtc-Python3-bindings and TestPython3Controller due to binary incompatibility in mc_rbdyn

### ISSUE THREAD

**Issue by orikuma** [mc-rtc/mc-rtc-superbuild#16]
I want to build mc_rtc from source using mc-rtc-superbuild.
I removed my old src and build directory and run following command.
```
cmake -S mc-rtc-superbuild -B mc-rtc-superbuild/build -DSOURCE_DESTINATION=$HOME/devel/src -DBUILD_DESTINATION=$HOME/devel/build -DWITH_HRP2=ON -DWITH_HRP5=ON
cmake --build mc-rtc-superbuild/build --config RelWithDebInfo
```
Then, mc_rtc failed to be built because test-mc_rtc-Python3-bindings and TestPython3Controller returned failure as follows.
```
96% tests passed, 3 tests failed out of 85

Total Test time (real) =  37.11 sec

The following tests FAILED:
          1 - test-mc_rtc-Python3-bindings (Failed)
         79 - TestPython3Controller (Failed)
         80 - TestPython3Log (Not Run)
Errors while running CTest
Output from these tests are in: /home/iori/devel/build/mc_rtc/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
CMake Error at /home/iori/jrl/mc-rtc-superbuild/cmake/scripts/cmake-with-prefix.cmake:20 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 8"
```
In `/home/iori/devel/build/mc_rtc/Testing/Temporary/LastTest.log`, test-mc_rtc-Python3-bindings and TestPython3Controller reported binary incompatibility error in importing mc_rbdyn.
```
----------------------------------------------------------
1/85 Testing: test-mc_rtc-Python3-bindings
1/85 Test: test-mc_rtc-Python3-bindings
Command: "/usr/bin/cmake" "-E" "env" "LD_LIBRARY_PATH=/home/iori/devel/build/mc_rtc/src:/home/iori/devel/build/mc_rtc/src:/home/iori/devel/build/mc_rtc/src:/home/iori/devel/build/mc_rtc/src:/home/iori/devel/build/mc_rtc/src:/home/iori/devel/build/mc_rtc/src:/home/iori/devel/build/mc_rtc/src:/home/iori/devel/build/mc_rtc/src:/home/iori/devel/build/mc_rtc/src:/home/iori/devel/build/mc_rtc/src:/home/iori/devel/build/mc_rtc/src/mc_control/fsm:/home/iori/devel/src/catkin_ws/devel/lib:/home/iori/devel/src/catkin_data_ws/devel/lib:/usr/local/lib:/home/iori/rviz/ros_ws/devel/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/usr/local/lib:/usr/local/lib:/usr/local/lib:/usr/local/lib:/usr/local/lib:/usr/local/lib" "/usr/bin/cmake" "-E" "env" "PYTHONPATH=.:/home/iori/devel/src/catkin_ws/devel/lib/python3/dist-packages:/home/iori/devel/src/catkin_data_ws/devel/lib/python3/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/home/iori/rviz/ros_ws/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages" "/usr/bin/cmake" "-E" "chdir" "/home/iori/devel/build/mc_rtc/binding/python/Python3/RelWithDebInfo/mc_rtc" "/usr/bin/python3.8" "-m" "pytest"
Directory: /home/iori/devel/build/mc_rtc/binding/python
"test-mc_rtc-Python3-bindings" start time: Apr 28 13:26 JST
Output:
----------------------------------------------------------
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-4.6.9, py-1.8.1, pluggy-0.13.0
rootdir: /home/iori/devel/build/mc_rtc/binding/python/Python3/RelWithDebInfo/mc_rtc
collected 0 items / 2 errors

==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_mc_rtc.py _____________________
tests/test_mc_rtc.py:5: in <module>
    import mc_rtc
mc_rtc/__init__.py:1: in <module>
    import mc_control
mc_control/__init__.py:1: in <module>
    from . import fsm
mc_control/fsm/__init__.py:1: in <module>
    from .fsm import *
fsm.pyx:1: in init mc_control.fsm.fsm
    ???
mc_rbdyn.pxd:16: in init mc_control.mc_control
    ???
mc_rbdyn/__init__.py:1: in <module>
    from .mc_rbdyn import *
parsers.pxd:12: in init mc_rbdyn.mc_rbdyn
    ???
E   ValueError: rbdyn.parsers.parsers.GeometryMesh size changed, may indicate binary incompatibility. Expected 80 from C header, got 56 from PyObject
___________________ ERROR collecting tests/test_mc_tasks.py ____________________
tests/test_mc_tasks.py:5: in <module>
    import mc_solver
mc_solver/__init__.py:1: in <module>
    from .mc_solver import *
mc_rbdyn.pxd:16: in init mc_solver.mc_solver
    ???
mc_rbdyn/__init__.py:1: in <module>
    from .mc_rbdyn import *
mc_rbdyn.pyx:42: in init mc_rbdyn.mc_rbdyn
    ???
E   AttributeError: type object 'mc_rbdyn.mc_rbdyn.Collision' has no attribute '__reduce_cython__'
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 2 error in 0.17 seconds ============================
<end of output>
Test time =   0.31 sec
----------------------------------------------------------
Test Failed.
"test-mc_rtc-Python3-bindings" end time: Apr 28 13:26 JST
"test-mc_rtc-Python3-bindings" time elapsed: 00:00:00
----------------------------------------------------------
```
```
----------------------------------------------------------

79/85 Testing: TestPython3Controller
79/85 Test: TestPython3Controller
Command: "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/home/iori/devel/build/mc_rtc/binding/python/Python3/RelWithDebInfo/mc_rtc:/home/iori/devel/src/mc_rtc/tests/controllers:/home/iori/devel/src/catkin_ws/devel/lib/python3/dist-packages:/home/iori/devel/src/catkin_data_ws/devel/lib/python3/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/home/iori/rviz/ros_ws/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3/dist-packages:/usr/local/lib/python3.8/dist-packages" "/usr/bin/cmake" "-E" "env" "LD_LIBRARY_PATH=/home/iori/devel/build/mc_rtc/src/mc_control/fsm:/home/iori/devel/build/mc_rtc/src:/home/iori/devel/src/catkin_ws/devel/lib:/home/iori/devel/src/catkin_data_ws/devel/lib:/usr/local/lib:/home/iori/rviz/ros_ws/devel/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/usr/local/lib:/usr/local/lib:/usr/local/lib:/usr/local/lib:/usr/local/lib:/usr/local/lib" "/home/iori/devel/build/mc_rtc/tests/controllers/ControllerRun_TestPython3Controller"
Directory: /home/iori/devel/build/mc_rtc/tests/controllers
"TestPython3Controller" start time: Apr 28 13:27 JST
Output:
----------------------------------------------------------
Running 1 test case...
[info] Loading default global configuration /usr/local/etc/mc_rtc.yaml
[info] Loading additional global configuration /home/iori/.config/mc_rtc/mc_rtc.yaml
[info] Loading additional global configuration /home/iori/devel/build/mc_rtc/tests/controllers/TestPython3/mc_rtc-TestPython3.conf
[warning] Aliases env/beam was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/box was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/box_table was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/chair was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/corniche was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/crapahut was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/crapahut_bricks was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/door was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/drc_terrain was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/ground was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/litter was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/platform was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/pole was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/printer was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/seesaw was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/table was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/table_printer was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/valve was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases env/valve_handle was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/env_aliases.yml will prevail
[warning] Aliases object/box was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/object_aliases.yml will prevail
[warning] Aliases object/door was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/object_aliases.yml will prevail
[warning] Aliases object/litter was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/object_aliases.yml will prevail
[warning] Aliases object/pole was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/object_aliases.yml will prevail
[warning] Aliases object/printer was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/object_aliases.yml will prevail
[warning] Aliases object/seesaw was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/object_aliases.yml will prevail
[warning] Aliases object/valve was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/object_aliases.yml will prevail
[warning] Aliases object/valve_handle was already declared, new declaration from /home/iori/devel/build/mc_rtc/src/mc_robots/aliases/object_aliases.yml will prevail
[info] GUI server enabled
[info] Will serve data on:
[info] - ipc:///tmp/mc_rtc_pub.ipc
[info] - tcp://*:4242
[info] Will handle requests on:
[info] - ipc:///tmp/mc_rtc_rep.ipc
[info] - tcp://*:4343
[info] Enabled plugins: Plugin0
[info] Loading additional plugin configuration: /home/iori/devel/build/mc_rtc/tests/controllers/TestPlugin/etc/Plugin0.yaml
[info] Create controller Python3
[info] [PythonController] Running with Python 3.8.10
[info] [PythonController] sys.path: ['/home/iori/devel/build/mc_rtc/binding/python/Python3/RelWithDebInfo/mc_rtc', '/home/iori/devel/src/mc_rtc/tests/controllers', '/home/iori/devel/src/catkin_ws/devel/lib/python3/dist-packages', '/home/iori/devel/src/catkin_data_ws/devel/lib/python3/dist-packages', '/usr/local/lib/python3/dist-packages', '/usr/local/lib/python3.8/dist-packages', '/home/iori/rviz/ros_ws/devel/lib/python3/dist-packages', '/opt/ros/noetic/lib/python3/dist-packages', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/iori/.local/lib/python3.8/site-packages', '/usr/lib/python3/dist-packages']
Traceback (most recent call last):
  File "/home/iori/devel/build/mc_rtc/binding/python/Python3/RelWithDebInfo/mc_rtc/mc_rbdyn/__init__.py", line 1, in <module>
    from .mc_rbdyn import *
  File "parsers.pxd", line 12, in init mc_rbdyn.mc_rbdyn
ValueError: rbdyn.parsers.parsers.GeometryMesh size changed, may indicate binary incompatibility. Expected 80 from C header, got 56 from PyObject
Traceback (most recent call last):
  File "/home/iori/devel/src/mc_rtc/tests/controllers/test_python/__init__.py", line 1, in <module>
    from .test_python import TestPythonController
  File "/home/iori/devel/src/mc_rtc/tests/controllers/test_python/test_python.py", line 7, in <module>
    import mc_rbdyn
  File "/home/iori/devel/build/mc_rtc/binding/python/Python3/RelWithDebInfo/mc_rtc/mc_rbdyn/__init__.py", line 1, in <module>
    from .mc_rbdyn import *
  File "mc_rbdyn.pyx", line 42, in init mc_rbdyn.mc_rbdyn
AttributeError: type object 'mc_rbdyn.mc_rbdyn.Collision' has no attribute '__reduce_cython__'
unknown location(0): [4;31;49mfatal error: in "RUN": memory access violation at address: 0x00000008: no mapping at fault address[0;39;49m
/home/iori/devel/src/mc_rtc/tests/test_global_controller_run.cpp(14): [1;36;49mlast checkpoint: "RUN" test entry[0;39;49m

[1;31;49m*** 1 failure is detected in the test module "Master Test Suite"
[0;39;49m
<end of output>
Test time =   0.19 sec
----------------------------------------------------------
Test Failed.
"TestPython3Controller" end time: Apr 28 13:27 JST
"TestPython3Controller" time elapsed: 00:00:00
----------------------------------------------------------

Failed test dependencies: TestPython3Controller
```

How can I solve this problem?

**Comment by gergondet** [comment]
Hi @orikuma 

This might be due to the recent changes in RBDyn bindings' build.

Can you check where the rbdyn bindings are installed, e.g., in a Python interpreter:
```python
import rbdyn
rbdyn
```

Then go to the folder this points to (if you install in /usr/local it would be /usr/local/lib/python3.8/dist-packages), I think there's one folder and two files to remove:
- in the rbdyn folder there will be 4 .so files: `rbdyn/rbdyn.so` and `rbdyn/parsers/parsers.so` should stay and the other two (`rbdyn/rbdyn-cpython-38-x86_64-linux-gnu.so` and `rbdyn/parsers/parsers-cpython-38-x86_64-linux-gnu.so` should be removed)
- the `rbdyn-[something].dist-info` should be removed as well

**Comment by orikuma** [comment]
I checked the directory which has rbdyn as follows.
```sh
$ ipython3
Python 3.8.10 (default, Mar 13 2023, 10:26:41)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import rbdyn

In [2]: rbdyn
Out[2]: <module 'rbdyn' from '/usr/local/lib/python3.8/dist-packages/rbdyn/__init__.py'>
```
In `/usr/local/lib/python3.8/dist-packages/rbdyn`, I had the following files.
```
$ ls /usr/local/lib/python3.8/dist-packages/rbdyn
__init__.py  __pycache__  c_rbdyn.pxd  parsers  rbdyn.cpython-38-x86_64-linux-gnu.so  rbdyn.pxd  rbdyn.so
$ ls /usr/local/lib/python3.8/dist-packages/rbdyn/parsers/
__init__.py  __pycache__  c_parsers.pxd  parsers.cpython-38-x86_64-linux-gnu.so  parsers.pxd  parsers.so
```
I removed `rbdyn.cpython-38-x86_64-linux-gnu.so` and  `parsers/parsers.cpython-38-x86_64-linux-gnu.so`.
I also removed `/usr/local/lib/python3.8/dist-packages/rbdyn-1.7.2_7063a85.dist-info/`.
After that, I could build mc_rtc without the above failure.
Thank you for your help.

**Comment by gergondet** [comment]
Thanks for the update.

Sorry for the trouble, I pushed a fix to [jrl-cmakemodules](https://github.com/jrl-umi3218/jrl-cmakemodules/commit/7cf918642ffff34e6960b240aae87b0414c28860) and put it in RBDyn/Tasks/mc_rtc to do this cleanup automatically
