### ISSUE TITLE
[macos] Cython not found

### ISSUE THREAD

**Issue by fkanehiro** [mc-rtc/mc-rtc-superbuild#21]
I'm trying to install on macos.
Building `Eigen3ToPython` fails with the following error messages.
```
Traceback (most recent call last):
  File "/Users/kanehiro/workspace/build/Eigen3ToPython/python3/RelWithDebInfo/setup.py", line 12, in <module>
    pkg_resources.require(pkg)
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 868, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Cython>=0.2' distribution was not found and is required by the application
ninja: build stopped: subcommand failed.
CMake Error at /Users/kanehiro/workspace/mc-rtc-superbuild/cmake/scripts/cmake-with-prefix.cmake:20 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"
```

Cython 0.29 is installed.
```
% brew info cython
==> cython: stable 0.29.35 (bottled) [keg-only]
Compiler for writing C extensions for the Python language
https://cython.org/
/usr/local/Cellar/cython/0.29.35 (325 files, 6.8MB)
  Poured from bottle using the formulae.brew.sh API on 2023-05-29 at 00:32:36
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/cython.rb
License: Apache-2.0
==> Dependencies
Required: python@3.11 ✔
==> Caveats
cython is keg-only, which means it was not symlinked into /usr/local,
because this formula is mainly used internally by other formulae.
Users are advised to use `pip` to install cython.

If you need to have cython first in your PATH, run:
  echo 'export PATH="/usr/local/opt/cython/bin:$PATH"' >> ~/.zshrc
==> Analytics
install: 24 (30 days), 124 (90 days), 24,289 (365 days)
install-on-request: 13 (30 days), 86 (90 days), 18,741 (365 days)
build-error: 0 (30 days)
```

**Comment by gergondet** [comment]
Hi @fkanehiro 

Can you give it a try with the latest version? It seems Cython is keg-only and brew recommends installing it via pip so I have modified superbuild to do that.

**Comment by fkanehiro** [comment]
Thanks, @gergondet 
After manually installing `coverage` and `pytest`, I could complete the compilation of `Eigen3ToPython`.

**Comment by fkanehiro** [comment]
But now `sch-core` is failing with cython related messages.
```
Error compiling Cython file:
------------------------------------------------------------
...
#
# Copyright 2012-2019 CNRS-UM LIRMM, CNRS-AIST JRL
#

from eigen.c_eigen cimport Vector3d
from sva.c_sva cimport *
^
------------------------------------------------------------

sch/c_sch.pxd:6:0: 'sva/c_sva.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from sva.c_sva cimport *

from c_sch cimport *

cdef extern from "sch_wrapper.hpp" namespace "sch":
  void transform(S_Object & obj, const PTransformd&)
                                      ^
------------------------------------------------------------

sch/c_sch_private.pxd:11:39: 'PTransformd' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
#

cimport c_sch
cimport c_sch_private
cimport eigen.eigen as eigen
cimport sva.sva as sva
       ^
------------------------------------------------------------

sch/sch.pyx:10:8: 'sva/sva.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
    if self.__own_impl and isinstance(self, S_Object):
      del self.impl
  def __cinit__(self):
    self.__own_impl = True
    self.impl = NULL
  def transform(self, sva.PTransformd trans):
                     ^
------------------------------------------------------------

sch/sch.pyx:22:22: 'PTransformd' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
      del self.impl
  def __cinit__(self):
    self.__own_impl = True
    self.impl = NULL
  def transform(self, sva.PTransformd trans):
    c_sch_private.transform(deref(self.impl), deref(trans.impl))
                                             ^
------------------------------------------------------------

sch/sch.pyx:23:46: Invalid operand type for '*' (Python object)
Compiling sch/sch.pyx because it changed.
[1/1] Cythonizing sch/sch.pyx
Traceback (most recent call last):
  File "/Users/kanehiro/workspace/build/sch-core-python/python3/RelWithDebInfo/setup.py", line 88, in <module>
    extensions = cythonize(extensions)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1115, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1238, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: sch/sch.pyx
ninja: build stopped: subcommand failed.
CMake Error at /Users/kanehiro/workspace/mc-rtc-superbuild/cmake/scripts/cmake-with-prefix.cmake:20 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"
```

**Comment by gergondet** [comment]
Hi @fkanehiro 

This should be fixed by updating SpaceVecAlg (or run `make update-SpaceVecAlg` in superbuild) and having the correct PYTHONPATH is the install prefix is not `/usr/local`

**Comment by fkanehiro** [comment]
> having the correct PYTHONPATH is the install prefix is not /usr/local

Thank you for pointing this out. At some point, `python3` was upgrade from 3.9 to 3.11.
I updated `.zshrc`.

At the end of installation of  `SpaceVecAlg`, the 7th test failed with the following messages.
```
________________ ERROR collecting tests/test_sva_containers.py _________________
ImportError while importing test module '/Users/kanehiro/workspace/build/SpaceVecAlg/binding/python/Python3/RelWithDebInfo/sva/tests/test_sva_containers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_sva_containers.py:10: in <module>
    import sva
sva/__init__.py:1: in <module>
    from .sva import *
E   ModuleNotFoundError: No module named 'sva.sva'
```

**Comment by gergondet** [comment]
@fkanehiro thanks for reporting this. I have updated SpaceVecAlg to fix this but I think it will fail next in RBDyn/Tasks/mc_rtc and I'll update the submodule to circumvent that there as well

The underlying problem is that we were generating `.dylib` files for the bindings in OSX but those are not loaded by Python on this platform (only `.so` are considered)

**Comment by gergondet** [comment]
I'm closing this. The macOS CI of superbuild now includes the Python bindings and it has been running steadily.

Since then I have also introduced fixes for:
- building the bindings with the recently release Cython 3.0
- working around an issue introduced in recent CMake versions
